# Generated by Django 5.0.7 on 2024-07-15 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_bd', '0005_category_category_name_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type_post_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type_post_ru',
        ),
    ]
