# Generated by Django 5.0.6 on 2024-07-08 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_bd', '0006_post_text_en_us_post_text_ru_post_title_en_us_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='type_post_en_us',
        ),
        migrations.RemoveField(
            model_name='post',
            name='type_post_ru',
        ),
    ]
